# The socks5 proxy will bind to this addess. You should probably use an address
# on the loopback adapter.
# Defaults to "127.0.0.1:5757"
bind: 127.0.0.1:5757

# For a list of valid log levels see https://github.com/sirupsen/logrus/blob/bdc0db8ead3853c56b7cd1ac2ba4e11b47d7da6b/logrus.go#L25
# Defaults to "info"
loglevel: info

# One of: "text", "json"
logformat: text

# Specify a list of rules. Rules are checked the order specified. Search for a
# matching rule ends on first match. Eeach rule specifies one forwarder. See
# details on forwarder at the bottom of the file.
rules:
    - subnets:
        - 10.0.1.0/24
        - 10.5.0.0/16
      forwarder:
          type: socks5
          address: 127.0.0.1:5050

    - subnets:
        - 10.10.4.0/24
      forwarder:
          type: direct

    - subnets:
        - 10.10.0.0/16
      forwarder:
          type: socks5
          address: 127.0.0.1:5060

defaultForwarder:
    type: direct

# Forwarders (in rules, and the defaultForwarder) can be of type "socks5" or "direct".
# "direct" will connect to the remote address directy.
# "socks5" will forward the connection to another socks5 proxy.
